//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace empregos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anuncio
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public decimal preco { get; set; }
        public Nullable<decimal> medida { get; set; }
        public int idUsuario { get; set; }
        public int idCategoria { get; set; }
        public string foto1 { get; set; }
        public string foto2 { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
