//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace empregos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public Nullable<int> cpf { get; set; }
        public string telefone { get; set; }
        public string telefone2 { get; set; }
        public Nullable<int> cep { get; set; }
        public string rua { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string senha { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
    }
}
